apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: accommodation
data:
  DATABASE_URL: "postgresql://postgres:stays_password@db-host-placeholder:5432/stays_db"
  REDIS_URL: "redis://redis-service:6379/0"
  JWT_EXPIRE: "30"
  REFRESH_EXPIRE: "7"
  SERVICE_PORT: "8000"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: accommodation
type: Opaque
stringData:
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "stays_password"
  JWT_SECRET: "local-dev-secret-minimum-32-characters!!"
