apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: accommodation
data:
  DATABASE_URL: "postgresql://shoply:shoply1234@db-host-placeholder:5432/shoply"
  REDIS_URL: "redis://redis-host-placeholder:6379"
  POSTGRES_DB: "shoply"
  POSTGRES_USER: "shoply"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: accommodation
type: Opaque
stringData:
  POSTGRES_PASSWORD: "shoply1234"
  JWT_SECRET: "change-me-in-production"
