apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: accommodation
data:
  DATABASE_URL: "postgresql://shoply:shoply1234@db-host-placeholder:5432/shoply"
  REDIS_URL: "redis://redis-host-placeholder:6379"
  POSTGRES_DB: "shoply"
  POSTGRES_USER: "shoply"
  REDIS_HOST: "redis-host-placeholder"
  REDIS_PORT: "6379"
  USER_SERVICE_URL: "http://user-service:4005"
  PRODUCT_SERVICE_URL: "http://product-service:4001"
  INVENTORY_SERVICE_URL: "http://inventory-service:4002"
  ORDER_SERVICE_URL: "http://order-service:4003"
  PAYMENT_SERVICE_URL: "http://payment-service:4004"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: accommodation
type: Opaque
stringData:
  POSTGRES_PASSWORD: "shoply1234"
  POSTGRES_HOST: "db-host-placeholder"
  JWT_SECRET: "change-me-in-production"
