apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: accommodation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      nodeSelector:
        role: service
      containers:
      - name: user-service
        image: ghcr.io/ktk026/shoply-user:develop
        ports:
        - containerPort: 4005
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-secret

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: accommodation
spec:
  selector:
    app: user-service
  ports:
  - port: 4005
    targetPort: 4005
