apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: accommodation
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::367299441871:role/grafana-cloudwatch-role

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: accommodation
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: CloudWatch
      type: cloudwatch
      access: proxy
      isDefault: true
      jsonData:
        defaultRegion: ap-northeast-2
        authType: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: accommodation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        role: service
      serviceAccountName: grafana-sa
      containers:
      - name: grafana
        image: grafana/grafana:10.4.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin1234"
        - name: GF_AWS_DEFAULT_REGION
          value: "ap-northeast-2"
        volumeMounts:
        - name: datasource
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: datasource
        configMap:
          name: grafana-datasource

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: accommodation
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
