services:
  postgres:
    image: postgres:16-alpine
    container_name: shoply-postgres
    restart: always
    environment:
      POSTGRES_DB: shoply
      POSTGRES_USER: shoply
      POSTGRES_PASSWORD: shoply1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./init/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shoply -d shoply"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: always
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://shoply:shoply1234@postgres:5432/shoply?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    pid: host
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  postgres_data:
