apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - redis.yaml
  - frontend.yaml
  - gateway.yaml
  - user.yaml
  - product.yaml
  - inventory.yaml
  - order.yaml
  - payment.yaml
  - hpa.yaml
