apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: ops
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    receivers:
      - name: loki
        loki:
          url: http://10.0.9.53:3100/loki/api/v1/push
          streamLabels: { source: kubernetes-events }
    route: { routes: [{ match: [{ receiver: loki }] }] }