serviceAccount: { create: true }
rbac: { create: true }
daemonset: { enabled: true }
image: { repository: grafana/promtail, tag: 2.9.8 }
config:
  server: { http_listen_port: 9080 }
  clients: [{ url: http://10.0.9.53:3100/loki/api/v1/push }]
  positions: { filename: /run/promtail/positions.yaml }
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs: [{ role: pod }]
      relabel_configs:
        - { source_labels: [__meta_kubernetes_pod_node_name], target_label: node }
        - { action: replace, source_labels: [__meta_kubernetes_namespace], target_label: namespace }
        - { action: replace, source_labels: [__meta_kubernetes_pod_name], target_label: pod }
        - { action: replace, source_labels: [__meta_kubernetes_pod_container_name], target_label: container }
        - { action: replace, separator: /, source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name], target_label: __path__, replacement: /var/log/pods/*$1/*.log }