services:
  order-payment:
    build:
      context: .
    image: shoply-k6-loadtest:ec2
    container_name: shoply-k6-order-payment
    environment:
      SCENARIO: ${SCENARIO:-shoply-order-payment.js}
      BASE_URL: ${BASE_URL:-http://54.180.167.159}
      VUS: ${VUS:-100}
      DURATION: ${DURATION:-5m}
      SLEEP_SECONDS: ${SLEEP_SECONDS:-1}
      LOAD_PROFILE: ${LOAD_PROFILE:-ramp}
      ACCOUNT_COUNT: ${ACCOUNT_COUNT:-2000}
      TEST_PASSWORD: ${TEST_PASSWORD:-Test1234!}
      TEST_RUN_ID: ${TEST_RUN_ID:-ec2-order-payment}
      K6_OUTPUT: ${K6_OUTPUT:-experimental-prometheus-rw}
      K6_PROMETHEUS_RW_SERVER_URL: ${K6_PROMETHEUS_RW_SERVER_URL:-http://54.180.138.196:9090/api/v1/write}
    volumes:
      - ./results/${TEST_RUN_ID:-ec2-order-payment}:/results

  smoke:
    image: shoply-k6-loadtest:ec2
    build:
      context: .
    profiles:
      - scenarios
    environment:
      SCENARIO: shoply-smoke.js
      BASE_URL: ${BASE_URL:-http://54.180.167.159}
      VUS: ${VUS:-5}
      DURATION: ${DURATION:-30s}
      LOAD_PROFILE: ${LOAD_PROFILE:-ramp}
      ACCOUNT_COUNT: ${ACCOUNT_COUNT:-2000}
      TEST_PASSWORD: ${TEST_PASSWORD:-Test1234!}
      K6_OUTPUT: ${K6_OUTPUT:-experimental-prometheus-rw}
      K6_PROMETHEUS_RW_SERVER_URL: ${K6_PROMETHEUS_RW_SERVER_URL:-http://54.180.138.196:9090/api/v1/write}

  stable-flow:
    image: shoply-k6-loadtest:ec2
    build:
      context: .
    profiles:
      - scenarios
    environment:
      SCENARIO: scenario-1-stable-order-payment.js
      BASE_URL: ${BASE_URL:-http://54.180.167.159}
      LOAD_PROFILE: ${LOAD_PROFILE:-ramp}
      ACCOUNT_COUNT: ${ACCOUNT_COUNT:-2000}
      TEST_PASSWORD: ${TEST_PASSWORD:-Test1234!}
      K6_OUTPUT: ${K6_OUTPUT:-experimental-prometheus-rw}
      K6_PROMETHEUS_RW_SERVER_URL: ${K6_PROMETHEUS_RW_SERVER_URL:-http://54.180.138.196:9090/api/v1/write}
