services:
  postgres:
    image: postgres:16-alpine
    container_name: shoply-postgres
    restart: always
    environment:
      POSTGRES_DB: shoply
      POSTGRES_USER: shoply
      POSTGRES_PASSWORD: shoply1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./init/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shoply -d shoply"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
