apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shoply

resources:
  - ../common
  - ingress-alb.yaml
  - serviceaccount.yaml

patchesStrategicMerge:
  - configmap-patch.yaml
