/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimesaleRouteImport } from './routes/timesale'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiPaymentsRouteImport } from './routes/api/payments'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'

const TimesaleRoute = TimesaleRouteImport.update({
  id: '/timesale',
  path: '/timesale',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/timesale': typeof TimesaleRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/timesale': typeof TimesaleRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/stats': typeof StatsRoute
  '/timesale': typeof TimesaleRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/stats'
    | '/timesale'
    | '/api/orders'
    | '/api/payments'
    | '/api/products'
    | '/api/stats'
    | '/products/$productId'
    | '/api/auth/login'
    | '/api/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/stats'
    | '/timesale'
    | '/api/orders'
    | '/api/payments'
    | '/api/products'
    | '/api/stats'
    | '/products/$productId'
    | '/api/auth/login'
    | '/api/products/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/login'
    | '/stats'
    | '/timesale'
    | '/api/orders'
    | '/api/payments'
    | '/api/products'
    | '/api/stats'
    | '/products/$productId'
    | '/api/auth/login'
    | '/api/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  StatsRoute: typeof StatsRoute
  TimesaleRoute: typeof TimesaleRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timesale': {
      id: '/timesale'
      path: '/timesale'
      fullPath: '/timesale'
      preLoaderRoute: typeof TimesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  StatsRoute: StatsRoute,
  TimesaleRoute: TimesaleRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
